In [1]:
import numpy as np
import pandas as pd

#!pip install matplotlib
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
#matplotlib.use('Qt5Agg')

import seaborn as sns

pd.set_option('display.max_columns', 50) #include to avoid ... in middle of display

In [2]:
#OPTIONAL: Load it only once per session, and save it, so we don't waste time
try:
    _ = data_from_source_file_df
    print("Reusing source data")
except:
    print("Loading source data")
    data_from_source_file_df = pd.read_csv("hotel_clean_up.csv")
data_df = data_from_source_file_df

Loading source data


In [9]:
prev_cancels = data_df["previous_cancellations"]
prev_not_cancels = data_df["previous_bookings_not_canceled"]  # 67
adults = data_df["adults"] # 67 62
booking_changes = data_df["booking_changes"] # 67 62 62

is_canceled = data_df["is_canceled"]
## prev cancel vs prev not cancelled 67 
## cancel vs adult 67
## prev_cancels vs booking_changes 67


In [10]:
adults_book_change_data = [[l,p] for l,p in zip(prev_cancels, prev_not_cancels)]

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(adults_book_change_data, is_canceled, shuffle=True, test_size=0.2, random_state=20)

In [12]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [13]:
from sklearn import tree

clf = tree.DecisionTreeRegressor()
clf = clf.fit(x_train, y_train)

In [14]:
clf.score(x_test,y_test)

0.09511655939930719

In [2]:

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

cancer = load_breast_cancer()

In [3]:
print(cancer.data)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
